/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LivestreamRouteImport } from './routes/livestream'
import { Route as IndexRouteImport } from './routes/index'

const LivestreamRoute = LivestreamRouteImport.update({
  id: '/livestream',
  path: '/livestream',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/livestream': typeof LivestreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/livestream': typeof LivestreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/livestream': typeof LivestreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/livestream'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/livestream'
  id: '__root__' | '/' | '/livestream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LivestreamRoute: typeof LivestreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/livestream': {
      id: '/livestream'
      path: '/livestream'
      fullPath: '/livestream'
      preLoaderRoute: typeof LivestreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LivestreamRoute: LivestreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
